apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rabbitmq.name }}
  namespace: {{ .Values.namespaces.application }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: salesuser
  RABBITMQ_DEFAULT_PASS: salespassword